services:
  
  evs-app:
    image: evs.app
    container_name: evs-app
    build:
      context: .
      dockerfile: EVS.App/Dockerfile
    environment:
      - RabbitMQ__Host=amqp://evs-rabbitMq:5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=test
      - SMTP_Options__Host=${SMTP_OPTIONS__HOST}
      - SMTP_Options__Port=${SMTP_OPTIONS__PORT}
      - SMTP_Options__Username=${SMTP_OPTIONS__USERNAME}
      - SMTP_Options__Password=${SMTP_OPTIONS__PASSWORD}
      - SMTP_Options__Name=${SMTP_OPTIONS__NAME}
    ports:
      - "8080:8080"
    networks:
      - evs-app-network
    volumes:
      - app-data:/app/appData
    depends_on:
      - evs-database
      - evs-rabbitMq
      
  evs-seq:
    image: datalust/seq:latest
    container_name: evs-seq
    ports:
      - "5341:5341"
      - "8082:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq-data:/data
    networks:
      - evs-app-network
      
  evs-database:
    image: postgres:latest
    container_name: evs-database
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432" 
    networks:
      - evs-app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  evs-pgadmin:
    image: dpage/pgadmin4
    container_name: evs-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8083:80"
    networks:
      - evs-app-network
    depends_on:
      - evs-database
      
  evs-rabbitMq:
    image: rabbitmq:management-alpine
    container_name: evs-rabbitMq
    hostname: evs-rabbitMq
    volumes:
      - rabbit-data:/var/lib/rabbitmq
      - rabbit-logs:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: test
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - evs-app-network
              
networks:
  evs-app-network:
    driver: bridge

volumes:
  seq-data:
  postgres-data:
  rabbit-data:
  rabbit-logs:
  app-data: